---
- name: Install dependencies
  become: true
  ansible.builtin.package:
    name: git
    state: present

- name: Remove cronjob
  become: true
  ansible.builtin.cron:
    name: pve-agent
    job: "/var/lib/vz/snippets/pve-agent.sh"
    minute: "*/5"
    user: root
    state: absent

- name: Remove script
  become: true
  ansible.builtin.file:
    state: absent
    path: "/var/lib/vz/snippets/pve-agent.sh"

- name: Download script
  become: true
  ansible.builtin.git:
    repo: "{{ pve_agent_repository }}"
    dest: "/tmp/pve-agent"

- name: Install scripts
  become: true
  ansible.builtin.copy:
    remote_src: true
    src: "/tmp/pve-agent/{{ item }}"
    dest: "/{{ item }}"
    owner: root
    group: root
    mode: "0755"
  loop:
    - "usr/bin/pve-agent"
    - "usr/lib/systemd/system/pve-agent.service"
    - "usr/lib/systemd/system/pve-agent.timer"

- name: Reload systemd
  become: true
  ansible.builtin.systemd:
    daemon_reload: true

- name: Enable service
  become: true
  ansible.builtin.service:
    name: "pve-agent.timer"
    enabled: true

- name: Start service
  become: true
  ansible.builtin.service:
    name: "pve-agent.timer"
    state: started
